cmd/image-service/cmd/service.go
internal/artifacts/flavor.go
internal/artifacts/manager.go
internal/frontend/http/http.go
internal/frontend/http/image.go
internal/frontend/http/pxe.go
internal/frontend/http/registry.go
internal/profile/profile.go
internal/profile/profile_test.go

This appends a "virtual" (built on the fly) extension which contains flavor ID to all boot assets of Talos.
This allows to easily identify which flavor of Talos which asset was built with.
E.g.:
```
$ talosctl -n 172.20.0.2 get extensions -i
NODE   NAMESPACE   TYPE              ID   VERSION   NAME     VERSION
runtime     ExtensionStatus   0    1         flavor   376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
```
```yaml
node:
metadata:
namespace: runtime
type: ExtensionStatuses.runtime.talos.dev
id: 0
version: 1
owner: runtime.ExtensionStatusController
phase: running
created: 2023-09-07T14:06:03Z
updated: 2023-09-07T14:06:03Z
spec:
image: 0.sqsh
metadata:
name: flavor
version: 376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
author: Image Service …
```

feat: add a virtual extension with flavor ID to generated assets

---

.kres.yaml
Dockerfile
Makefile
README.md
cmd/image-service/cmd/options.go
cmd/image-service/cmd/service.go
cmd/image-service/flags.go
internal/artifacts/artifacts.go
internal/artifacts/fetch.go
internal/artifacts/flavor.go
internal/artifacts/manager.go
internal/artifacts/versions.go
internal/frontend/http/http.go
internal/frontend/http/image.go
internal/frontend/http/meta.go
internal/integration/download_test.go
internal/integration/flavor_test.go
internal/integration/integration_test.go
internal/integration/meta_test.go
internal/integration/registry_test.go
internal/profile/profile.go
internal/profile/profile_test.go

Fixes #13
This builds on top of extensions catalog (see
https://github.com/siderolabs/extensions/pull/225), and existing support for specifying extension in the flavor.
Image Service resolve the list of extensions requested for a specific version of Talos into a list of container images, pulls them, and attaches them to the image request.
Image Service also provides endpoints to get information about available Talos versions, supported extensions for each version, etc.
I also refactored a bit flow around fetching & verifying image to re-use it in other flows, added support for authentication to the registry.

feat: implement support for system extensions

---

cmd/image-factory/cmd/service.go
internal/frontend/http/registry.go
internal/schematic/storage/registry/registry.go

Pass auth to the registry frontend so that it correctly authenticates to the registry on uploads/checks.
Refactor the code in the registry frontend to use digest instead of tag when redirecting request for additional security.
In the schematic registry storage, push a manifest on top of raw blob to make sure it doesn't get garbage collected as orphaned. We never use the manifest though.

fix: various (small) fixes for registry operations

---

cmd/image-factory/cmd/options.go
cmd/image-factory/cmd/service.go
cmd/image-factory/flags.go
internal/artifacts/artifacts.go
internal/artifacts/manager.go

Adds support for using an insecure image registry without having to specify it as IP:PORT.

feat: add support for insecure image registry

---

cmd/image-factory/cmd/options.go
cmd/image-factory/cmd/service.go
cmd/image-factory/flags.go

Adds support for connecting to the internal endpoint of the public image repository without TLS.

feat: support insecure endpoint for internal repository

---

internal/frontend/http/registry.go

This was using wrong image name, so the check never succeeded resulting in re-build of the image each time.

fix: check the already built installer image correctly

---

README.md
cmd/image-factory/cmd/options.go
cmd/image-factory/cmd/service.go
cmd/image-factory/flags.go
internal/frontend/http/http.go
internal/frontend/http/registry.go
internal/image/signer/signer.go
internal/integration/integration_test.go
internal/integration/registry_test.go

Image Factory now signs the generated asset using cosign flow with a fixed key. Image Factory also verifies the signature before redirecting to the image. This way we ensure the consistency of the cache.
The signing ECDSA private key (PEM-encoded) should be supplied as `--signing-key-path` flag.
Fixes #29

feat: sign generated installer image

---

cmd/image-factory/cmd/options.go
cmd/image-factory/cmd/service.go
cmd/image-factory/flags.go

I forgot to implement it while doing asset caching.

fix: implement insecure option for cache repository

---

internal/profile/profile.go
internal/profile/profile_test.go

As `digital-ocean` has a dash, we need to do a little trick, as we should support both:
* `digital-ocean-amd64`
* `metal-rpi_generic-arm64`
The first has platform `digital-ocean`, while the second is platform `metal` and board `rpi_generic`.

fix: parse profiles for 'digital-ocean' platform

---

internal/frontend/http/registry.go

It seems that it requires us to load all image layers into memory, and that is extra work we could skip. We don't expect any actual validation errors, as the image index is built same way every time.

fix: skip validating image index before pushing

---

.github/workflows/ci.yaml
.github/workflows/slack-notify.yaml
Dockerfile
Makefile
internal/frontend/http/meta.go
internal/integration/meta_test.go
internal/integration/registry_test.go
internal/integration/schematic_test.go
pkg/client/client.go
pkg/client/options.go

The client provides methods to create schematics, Talos versions, and extensions version.
Fixes: #21

feat: implement HTTP API client

---

internal/artifacts/schematic.go
pkg/constants/constants.go

Make it const to simplify discovery of the Talos machine schematic IDs by third party services.

chore: define public const for the schematic ID extension name

---

README.md
cmd/image-factory/cmd/options.go
cmd/image-factory/cmd/service.go
cmd/image-factory/flags.go
internal/frontend/http/http.go
internal/frontend/http/pxe.go
internal/frontend/http/ui.go

iPXE can't support booting from modern certificate chains issued by Let's Encrypt, so provide an option to use custom (less secure?) endpoint for PXE booting.

feat: provide configuration for a custom PXE endpoint

---

internal/artifacts/artifacts.go
internal/artifacts/manager.go
internal/artifacts/versions.go
internal/frontend/http/ui.go
internal/integration/meta_test.go
pkg/client/client.go
pkg/client/errors.go

Now Image Factory filters out pre-release versions for all releases but the last one.
In the UI, now pre-release versions are shown.
Return proper 404 not found when someone requests something for an unsupported version.
Fixes #75 
(the versions before 1.4.0 are not yet enabled in Image Factory, see #20)

fix: update Talos version listing

---

internal/artifacts/versions.go
internal/frontend/http/meta.go
internal/frontend/http/templates/schematic-config.html
pkg/client/client.go

Get `descriptions.yaml` from the same image as we use for getting `image-digests`.
Read it and add this data to each extension info.
Return that in the `version/:version/extensions/official` API response.

feat: fetch extensions descriptions from the extensions image

---

.kres.yaml
Dockerfile
Makefile

Upstream issue was fixed: https://github.com/golang/go/issues/64112#issuecomment-1894443979

chore: re-enable govulncheck

---

internal/artifacts/manager.go

Starting with 1.7.0-alpha.1, these are not present in the imager.

fix: ignore missing DTB and other SBC artifacts

---

internal/frontend/http/ui.go

In the UI, sort extensions alphabetically, so it doesn't matter which order you click the checkboxes.
Fixes #99

fix: sort extensions in the UI schematic generator

---

internal/profile/profile.go
internal/profile/profile_test.go

Some extensions have names in the manifest which are different from the container image names. This was fixed, but old Talos installs will still report wrong names.
Add a workaround to support name aliases for the known "bad" names.

fix: workaround extension name inconsistencies

---

internal/artifacts/manager.go

It should report the actual error from the task, not the `err`.

fix: misreported error

---

internal/profile/profile.go
internal/profile/profile_test.go

Alias old nvidia extensions schema to LTS versions so upgrades work and users are not surprised with a new major version.
Part of: https://github.com/siderolabs/talos/issues/9086

chore: alias nvidia extensions to lts versions

---

internal/frontend/http/ui.go
internal/integration/download_test.go

It is an internal extension, so we don't want to list it on the UI.

feat: hide Talos metal agent extension on the UI

---

internal/profile/profile.go
internal/profile/profile_test.go

Alias i915/amdgpu extensions to new name.
Ref: https://github.com/siderolabs/extensions/pull/526
Part of: https://github.com/siderolabs/talos/issues/9728

chore: alias i915/amdgpu extensions to new name

---

pkg/metadata/sbcs.go

Adds the SBC Turing RK1 as an option to the factory.talos.dev interactive web interface.

feat: add Turing RK1 as option

---

cmd/image-factory/cmd/service.go

Support gcr.io keychain for registry auth.

chore: support gcr.io keychain for registry auth

---

pkg/metadata/platforms.go

Per https://github.com/siderolabs/terraform-provider-talos/issues/222, set SecureBootSupported flag for nocloud images. Images are available and confirmed to work with Secure Boot on Proxmox, setting this here so the Terraform provider can decern that Secure Boot images are available.

feat: Set Secure Boot support in metadata for nocloud platform

---

go.mod
go.sum

Lower memory usage even further (600Mib -> 80Mib). More details https://github.com/Foxboron/go-uefi/pull/24.

chore: update go-uefi module

---

internal/frontend/http/secureboot.ipxe
internal/frontend/http/standard.ipxe
internal/integration/pxe_test.go

fix for `Initramfs unpacking failed: invalid magic at start of compressed`
While using image generated from the image factory I was getting `Initramfs unpacking failed: invalid magic at start of compressed` when booting. https://github.com/ipxe/ipxe/discussions/1329. I tried the suggestion adding `imgfree` before kernel command and was able to boot into talos.

add imgfree to standard.ipxe boot script

---

internal/frontend/http/locales/active.en.yaml
internal/frontend/http/locales/active.ru.yaml

In each translation, use native language name, so that if someone accidentally switches to the language they don't understand, they know a way to switch back.

fix: specify each language natively

---

.golangci.yml
.kres.yaml
Dockerfile
Makefile

The cron job that updates to Talos main used a docker step that got cached, fix by always re-running `go get -u` commands.

fix(ci): image factory cron

---

.github/workflows/ci.yaml
.github/workflows/integration-talos-main-cron.yaml
.kres.yaml
Dockerfile
Makefile
cmd/image-factory/cmd/options.go
cmd/image-factory/cmd/service.go
go.mod
internal/artifacts/artifacts.go
internal/artifacts/manager.go
internal/asset/asset.go
internal/asset/cache.go
internal/frontend/http/http.go
internal/image/signer/signer.go
internal/integration/integration_test.go
internal/remotewrap/internal/refresher/refresher.go
internal/remotewrap/internal/refresher/refresher_test.go
internal/remotewrap/remotewrap.go
internal/schematic/storage/registry/registry.go

This is not a fix, but a bit of a workaround for issues in the upstream library.
Use a refresh on interval strategy to ensure that both remote pushers and pullers are refreshed.
Fixes #231
Fixes #235

fix: refresh remote pullers and pushers on interval

---

README.md

Add some air-gapped examples as well.
Fixes #262

docs: document source images used

---

internal/artifacts/versions.go

Without this fix, Talos v1.11.0-rc.0 is not visible.

fix: don't filter out `rc` versions

---

internal/frontend/http/templates/wizard-final.html
internal/integration/download_test.go
internal/integration/pxe_test.go
internal/integration/registry_test.go
internal/integration/talosctl_test.go

It was showing as 'missing translation' confusingly.

fix: translation ID
