- README.md
- cmd/image-service/cmd/options.go
- cmd/image-service/cmd/service.go
- cmd/image-service/flags.go
- go.mod
- go.sum
- internal/configuration/storage/inmem/inmem.go
- internal/configuration/storage/storage.go
- internal/frontend/http/configuration.go
- internal/frontend/http/http.go
- internal/frontend/http/image.go
- internal/frontend/http/pxe.go
- internal/frontend/http/secureboot.ipxe
- internal/frontend/http/standard.ipxe
- internal/integration/configuration_test.go
- internal/integration/download_test.go
- internal/integration/integration_test.go
- internal/integration/pxe_test.go
- internal/profile/profile.go
- pkg/configuration/configuration.go
Also, improve error reporting and add more tests for invalid requests.
Fixes #7
> feat: implement PXE frontend

- go.mod
- go.sum
- internal/integration/discarder_test.go
- internal/integration/download_test.go
- internal/integration/initramfs_test.go
* fix depmod for non-current kernel versions
* fix early u-code building
Add tests for initramfs contents.
> fix: import Talos with initramfs generation fixes

- internal/frontend/http/templates/schematic.html
Remove errant space in web UI asset links.
> fix: asset links

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- Dockerfile
- Makefile
> chore: rekres

- README.md
- internal/integration/download_test.go
- internal/integration/schematic_test.go
- internal/profile/profile.go
- pkg/schematic/schematic.go
- pkg/schematic/schematic_test.go
> feat: support 'META' customization in schematics

- .dockerignore
- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- CHANGELOG.md
- Dockerfile
- Makefile
- hack/release.toml
- internal/integration/download_test.go
This is the official v0.1.1 release.
> release(v0.1.1): prepare release

- CHANGELOG.md
This is the official v0.1.2 release.
> release(v0.1.2): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.2.1 release.
> release(v0.2.1): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.2.2 release.
> release(v0.2.2): prepare release

- .dockerignore
- .github/workflows/ci.yaml
- .kres.yaml
- Dockerfile
- Makefile
Run tailwindcss as part of build process.
> chore: run tailwindcss before creating image.

- CHANGELOG.md
- hack/release.toml
This is the official v0.2.3 release.
> release(v0.2.3): prepare release

- cmd/image-factory/cmd/options.go
- cmd/image-factory/cmd/service.go
- cmd/image-factory/flags.go
Allow usage of an insecure schematics repository
> feat: add support for -insecure-schematic-service-repository flag

- CHANGELOG.md
This is the official v0.3.0 release.
> release(v0.3.0): prepare release

- CHANGELOG.md
This is the official v0.3.1 release.
> release(v0.3.1): prepare release

- CHANGELOG.md
This is the official v0.3.2 release.
> release(v0.3.2): prepare release

- .kres.yaml
- CHANGELOG.md
- Dockerfile
- hack/release.toml
- internal/integration/download_test.go
- internal/integration/meta_test.go
- internal/integration/registry_test.go
This is the official v0.3.3 release.
> release(v0.3.3): prepare release

- .github/workflows/ci.yaml
- .golangci.yml
- Dockerfile
- Makefile
- internal/frontend/http/templates/wizard-versions.html
Corrected Typo in wizard-versions.html
> chore: correct typo in wizard-versions.html

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.2 release.
> release(v0.4.2): prepare release

- .github/workflows/ci.yaml
- .kres.yaml
> chore: build multi-arch image

- pkg/metadata/sbcs.go
Add info about Kobol Helios64 overlay.
> chore: add in new helios64 overlay

- cmd/image-factory/cmd/service.go
This provides better image reproducibility for output images.
> fix: set SOURCE_DATA_EPOCH

- internal/artifacts/schematic.go
The system extensions depends on a quirk, but the cache was based only on schematic ID. Adjust cache ID.
There was another bug which masked this bug - the schematic extension cache wasn't used, so the bug could have only been triggered on strictly concurrent schematic extension build for different versions of Talos.
> fix: cache generated system extension image correctly

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.0 release.
> release(v0.5.0): prepare release

- .kres.yaml
- CHANGELOG.md
- Makefile
This is the official v0.6.2 release.
> release(v0.6.2): prepare release

- CHANGELOG.md
This is the official v0.6.7 release.
> release(v0.6.7): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.9 release.
> release(v0.6.9): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.7.3 release.
> release(v0.7.3): prepare release

- .codecov.yml
- .github/workflows/ci.yaml
- .gitignore
- .kres.yaml
- Makefile
Run them so that coverage goes to codecov merged with unit-test coverage.
> test: capture test coverage for integration tests

- internal/integration/pxe_test.go
- internal/profile/profile.go
Closes #268
Also update the integration tests for PXE frontend.
> fix: support iPXE aliases for architectures

- CHANGELOG.md
- hack/release.toml
This is the official v0.7.5 release.
> release(v0.7.5): prepare release

- internal/frontend/http/locales/active.en.yaml
- internal/frontend/http/locales/active.pl.yaml
- internal/frontend/http/locales/active.ru.yaml
Added a new translation (Polish) for the Image Factory UI.
> docs: add new translation

- cmd/image-factory/cmd/options.go
- cmd/image-factory/cmd/service.go
- cmd/image-factory/flags.go
- internal/asset/cache/s3/s3.go
Allow configuration of S3 Region by adding extra flag.
> fix: add region support

- README.md
Readme was lacking part about configuring S3 and CDN cache.
I added required flags and described process of configuring it,
as well as local testing with Min.IO and Nginx.
> docs(image-factory): add info about S3 cache and CDN

- CHANGELOG.md
- hack/release.toml
> release(v0.8.0): prepare release

- .dockerignore
- .github/workflows/ci.yaml
- .github/workflows/integration-cdn-talos-main-cron.yaml
- .github/workflows/integration-direct-talos-main-cron.yaml
- .github/workflows/integration-s3-talos-main-cron.yaml
- .github/workflows/lock.yml
- .github/workflows/slack-notify-ci-failure.yaml
- .github/workflows/stale.yml
- .kres.yaml
- Dockerfile
- Makefile
- cmd/image-factory/cmd/options.go
- cmd/image-factory/cmd/service.go
- hack/govulncheck.sh
- internal/asset/asset.go
- internal/frontend/http/http.go
- internal/integration/integration_test.go
- internal/integration/main_cdn_test.go
- internal/integration/main_direct_test.go
- internal/integration/main_s3_test.go
- internal/schematic/schematic.go
- internal/schematic/storage/cache/cache.go
- internal/schematic/storage/cache/cache_test.go
Introduce fallback mechanism when the `cache.Put` (or `cache.Get`) fails, so the image can be still delivered to end user.
> feat: fallback if S3 is missbehaving

- CHANGELOG.md
- hack/release.toml
This is the official v0.8.1 release.
> release(v0.8.1): prepare release

- internal/frontend/http/image.go
- internal/integration/download_test.go
- internal/integration/integration_test.go
- internal/integration/pxe_test.go
> fix: disable redirects to PXE
